name       : marco
version    : 1.20.3
release    : 13
source     :
    - https://pub.mate-desktop.org/releases/1.20/marco-1.20.3.tar.xz : 626817d148f93a81d3e0eb11c96cbb4a170536aa4b490aa68e5d47ea49a656a4
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pangoxft)
    - pkgconfig(sm)
    - pkgconfig(xcursor)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
