name       : marco
version    : 1.24.2
release    : 24
source     :
    - https://github.com/mate-desktop/marco/releases/download/v1.24.2/marco-1.24.2.tar.xz : 498350cb12fc4d9c7c4a0355102c17b50043fbab258d11ad41b7d698b4f042a7
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(sm)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - mate-common
    - yelp-tools
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
