name       : marco
version    : 1.14.2
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.14/marco-1.14.2.tar.xz : 31ab76950bd6f8e829c1c40be8cb53c0d77a17791137752d196e73f3d9e55be4
license    : GPL-2.0
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangoxft)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - pkgconfig(xcursor)
    - itstool
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %patch -p1 < $pkgfiles/0001-Start-late-to-fight-panel-race-condition.patch
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
