name       : marco
version    : 1.20.1
release    : 11
source     :
    - https://pub.mate-desktop.org/releases/1.20/marco-1.20.1.tar.xz : a44e4983f1f3bcf6460ded1677c3599d59ce4e2133cae0140680ee15d521dde2
license    : GPL-2.0-only
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pangoxft)
    - pkgconfig(sm)
    - pkgconfig(xcursor)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools-devel
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
