name       : marco
version    : 1.20.0
release    : 9
source     :
    - https://pub.mate-desktop.org/releases/1.20/marco-1.20.0.tar.xz : 999aae7a3535c982cb178f771b99885a7b0cc49957f972a75406c61222725a1d
license    : GPL-2.0
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(pangoxft)
    - pkgconfig(sm)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools-devel
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
