name       : marco
version    : 1.22.1
release    : 16
source     :
    - https://github.com/mate-desktop/marco/archive/v1.22.1.tar.gz : 0d9d264b0c2f7ed3a838b9e6037682e43b907d13e034d06e60dc1ef541b1ff78
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(sm)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - mate-common
    - yelp-tools
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
