name       : marco
version    : 1.27.0
release    : 27
source     :
    - https://github.com/mate-desktop/marco/releases/download/v1.27.0/marco-1.27.0.tar.xz : 4b5cafb6e67c2f42d705f5a812e7341b188eb1dab3e74b88329794c20b3327dd
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(sm)
    - pkgconfig(xpresent)
    - pkgconfig(xres)
    - pkgconfig(yelp-xsl)
    - itstool
    - mate-common
    - yelp-tools
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
