name       : marco
version    : 1.18.0
release    : 5
source     :
    - https://pub.mate-desktop.org/releases/1.18/marco-1.18.0.tar.xz : 9b273026bc739352b5287f9d804ffae2d873f7ee3fbe4d1d5673473eae2938a8
license    : GPL-2.0
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangoxft)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - pkgconfig(xcursor)
    - itstool
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %patch -p1 < $pkgfiles/0001-Start-late-to-fight-panel-race-condition.patch
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
