name       : marco
version    : 1.22.4
release    : 20
source     :
    - https://github.com/mate-desktop/marco/archive/v1.22.4.tar.gz : 20caf6e48a010f115ece80d70a92487a211500cfcca4f23486a0db115640fa3f
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(sm)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - mate-common
    - yelp-tools
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
