name       : marco
version    : 1.26.0
release    : 26
source     :
    - https://github.com/mate-desktop/marco/releases/download/v1.26.0/marco-1.26.0.tar.xz : f63c08cd8b07450ab3e33a04605c4f9e69522358884273b3cbcf30275eee5b05
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(sm)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - mate-common
    - yelp-tools
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
