name       : marco
version    : 1.18.2
release    : 8
source     :
    - https://pub.mate-desktop.org/releases/1.18/marco-1.18.2.tar.xz : c5a53e694b36f7630ecacd23c52cc30cd086e30896aa1a9461f2b169734d6f9c
license    : GPL-2.0
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pangoxft)
    - pkgconfig(sm)
    - pkgconfig(xft)
    - pkgconfig(xcursor)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - yelp-tools-devel
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
