name       : marco
version    : 1.22.2
release    : 17
source     :
    - https://github.com/mate-desktop/marco/archive/v1.22.2.tar.gz : 0cfc7f12a5fbccac40eafc2a4df9f0b1d0014477154e8483cba8a6fd7c8b6f96
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Window manager of the MATE Desktop
description: |
    Window manager of the MATE Desktop
builddeps  :
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(sm)
    - pkgconfig(xpresent)
    - pkgconfig(yelp-xsl)
    - itstool
    - mate-common
    - yelp-tools
    - zenity
rundeps    :
    - mate-desktop
    - zenity
setup      : |
    %apply_patches
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
